reason=input("Enter reason ....\n")
date=input("Date .....\n")
print("\n")

print("Subject: Leave Application due to "+reason)
print("Dear Sir,\n")
print("Greetings of the day.")
print("Kindly grant me leave on "+date+", Since I am having "+reason+".")
print("Thanks and Regards,\n")
print("Er.Akhil P Jacob,\n")
print("Senior Robotics Engineer\n")
print("Inker Robotics Thrissur\n")
