'''
Designed and Developed by Akhil P Jacob
property of Hyper Library Dynamic Integrations

'''


from PyQt5 import QtCore, QtGui, QtWidgets
from Seeker import timeMapper
import AutomataLib


class MATTBOT(object):
    def mattbot(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(477, 358)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Graphix/MattBot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 451, 321))
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 0, 361, 281))
        self.label.setStyleSheet("border-image: url(Graphix/MattBot.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label_2.setStyleSheet("color: rgb(204, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(340, 250, 89, 25))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(22, 250, 301, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 421, 17))
        self.label_13.setStyleSheet("color: rgb(3, 0, 255);")
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 31, 17))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 20, 113, 25))
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 20, 89, 25))
        self.pushButton_2.setStyleSheet("color: rgb(204, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 20, 89, 25))
        self.pushButton_3.setStyleSheet("\n"
"color: rgb(3, 0, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 60, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 41, 20))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 100, 221, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 41, 20))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 100, 131, 25))
        self.pushButton_4.setStyleSheet("color: rgb(78, 154, 6);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 140, 131, 25))
        self.pushButton_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 180, 131, 25))
        self.pushButton_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 140, 281, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(150, 20, 211, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 111, 20))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 111, 20))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(3, 0, 255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 70, 211, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 120, 211, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(30, 120, 111, 20))
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 170, 211, 25))
        self.pushButton_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 210, 211, 25))
        self.pushButton_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(3, 0, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(330, 180, 101, 81))
        self.label_10.setStyleSheet("border-image: url(Graphix/ubuntu.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(180, 130, 131, 141))
        self.label_11.setStyleSheet("border-image: url(Graphix/HLEngine.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 141))
        self.label_12.setStyleSheet("border-image: url(Graphix/HLD.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 81, 17))
        self.label_3.setObjectName("label_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 10, 161, 25))
        self.pushButton_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(3, 0, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 50, 61, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(160, 50, 281, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 81, 17))
        self.label_14.setStyleSheet("color: rgb(204, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 80, 61, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(70, 270, 291, 20))
        self.label_15.setObjectName("label_15")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 261, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_3, "")


        self.pushButton.clicked.connect(self.seek)
        self.pushButton_2.clicked.connect(self.chatServer)
        self.pushButton_3.clicked.connect(self.chatClient)
        

        self.timer = QtCore.QTimer(Dialog)
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.displayTime)
        self.timer.start()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def displayTime(self):
        self.label_2.setText(QtCore.QDateTime.currentDateTime().time().toString())
        reminder=self.lineEdit_7.text()
        reminder_data=self.lineEdit_8.text()
        self.label_13.setText("Reminder: "+reminder_data)
        AutomataLib.automata(self.label_2.text(),reminder)
        
    def seek(self):
        import terminal
        data=self.lineEdit.text()
        terminal.terminalAccess(data)
        self.lineEdit.setText("")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MATTBOT 2020 ver 2.0"))
        self.label_2.setText(_translate("Dialog", "Loading..."))
        self.pushButton.setText(_translate("Dialog", "Ask"))
        self.label_13.setText(_translate("Dialog", ""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "MATTBOT"))
        self.label_4.setText(_translate("Dialog", "IP "))
        self.pushButton_2.setText(_translate("Dialog", "Start"))
        self.pushButton_3.setText(_translate("Dialog", "Join"))
        self.label_5.setText(_translate("Dialog", "NAME"))
        self.label_6.setText(_translate("Dialog", "TYPE"))
        self.pushButton_4.setText(_translate("Dialog", "Send"))
        self.pushButton_5.setText(_translate("Dialog", "Clear"))
        self.pushButton_6.setText(_translate("Dialog", "Disconnect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Chat"))
        self.comboBox.setItemText(0, _translate("Dialog", "None"))
        self.comboBox.setItemText(1, _translate("Dialog", "/dev/ttyUSB0"))
        self.comboBox.setItemText(2, _translate("Dialog", "/dev/ttyUSB1"))
        self.comboBox.setItemText(3, _translate("Dialog", "/dev/ttyUSB2"))
        self.comboBox.setItemText(4, _translate("Dialog", "/dev/ttyUSB3"))
        self.comboBox.setItemText(5, _translate("Dialog", "/dev/ttyACM0"))
        self.comboBox.setItemText(6, _translate("Dialog", "/dev/ttyACM1"))
        self.comboBox.setItemText(7, _translate("Dialog", "/dev/ttyACM2"))
        self.comboBox.setItemText(8, _translate("Dialog", "/dev/ttyACM3"))
        self.label_7.setText(_translate("Dialog", "Choose Device"))
        self.label_8.setText(_translate("Dialog", "Bluetooth MAC"))
        self.label_9.setText(_translate("Dialog", "Message Packet"))
        self.pushButton_7.setText(_translate("Dialog", "Send Packet via COM"))
        self.pushButton_8.setText(_translate("Dialog", "Send Packet via BT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Devices"))
        self.label_3.setText(_translate("Dialog", "Reminder"))
        self.pushButton_9.setText(_translate("Dialog", "Check for Updates"))
        self.label_14.setText(_translate("Dialog", "Shutdown"))
        self.label_15.setText(_translate("Dialog", "Designed and Developed by Akhil P Jacob"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = MATTBOT()
    ui.mattbot(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
